### ISSUE TITLE
[fixes]: Add a validation in login 

### ISSUE THREAD

**Issue by ak3264114** [maniyaom/Movie-Ticket-Booking#79] opened 2024-10-03 09:39 UTC
### Problem
- Users are currently able to call the login API using an invalid email format, allowing invalid emails to bypass frontend validation.

### Proposed Solution
- Implement a **regex validation** for the email field before submitting the form to ensure only valid email formats are accepted. This will prevent invalid emails from being submitted to the login API, improving security and user experience.

please assign this issue to me under hacktoberfest and gssoc-ext

**Comment by ak3264114** [comment] 2024-10-03 09:39
@maniyaom

**Comment by maniyaom** [comment] 2024-10-03 12:52
@ak3264114 This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue no. 77

**Closed** 2024-10-03 12:53 UTC
Labels: duplicate
