### ISSUE TITLE
There is no home page 

### ISSUE THREAD

**Issue by Khushi-51** [maniyaom/Movie-Ticket-Booking#85] opened 2024-10-03 13:55 UTC
I propose developing a comprehensive homepage for the Ticketify website to enhance user engagement and improve navigation. The key features I plan to implement include:

User-Friendly Design: The homepage will feature an intuitive layout with clear sections for movie listings, promotions, and quick access to ticket booking.

Visual Appeal: Incorporating high-quality images and engaging graphics will create a vibrant and attractive first impression, showcasing our brand and offerings effectively.

Responsive Functionality: The design will be fully responsive, ensuring an optimal viewing experience across all devices, including desktops, tablets, and smartphones.

Call-to-Action Elements: Prominent call-to-action buttons will guide users to book tickets easily, explore movie options, and access customer support.

Information Hub: The homepage will serve as an information hub, providing updates on new releases, special offers, and upcoming events to keep users informed and engaged.

By creating a dedicated homepage, we can improve user navigation, increase ticket bookings, and enhance the overall experience for our visitors. Please assign this task to me under GSSOC'24 Extended and Hacktoberfest. I'm excited to contribute to this vital aspect of our project!
![image](https://github.com/user-attachments/assets/c4724363-fe99-4463-ae11-aa5a5d7c47a5)

**Comment by maniyaom** [comment] 2024-10-03 17:13
@Khushi-51 This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue #71

**Closed by maniyaom** 2024-10-03 17:13 UTC
Labels: duplicate
