### ISSUE TITLE
Add a hero section

### ISSUE THREAD

**Issue by nishtha-902** [maniyaom/Movie-Ticket-Booking#92] opened 2024-10-03 18:21 UTC
@maniyaom please assign me this task I will create the best hero section suited for this website in accordance with the color theme

**Comment by maniyaom** [comment] 2024-10-04 09:45
@nishtha-902 This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue #71

**Closed by maniyaom** 2024-10-04 09:45 UTC
Labels: duplicate
