### ISSUE TITLE
Password visibility button

### ISSUE THREAD

**Issue by Devanshu1603** [maniyaom/Movie-Ticket-Booking#34] opened 2024-10-02 05:23 UTC
there is not any password visibility on of off button. Can you please assign me this under gssoc ext level so that i could contribute on this issue

**Comment by maniyaom** [comment] 2024-10-02 06:27
@Devanshu1603 This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue 27

**Closed by maniyaom** 2024-10-02 06:27 UTC
Labels: duplicate
