### ISSUE TITLE
Add homepage to the website

### ISSUE THREAD

**Issue by rutikakengal** [maniyaom/Movie-Ticket-Booking#99] opened 2024-10-04 06:22 UTC
In this website home section is not visibling and add logo to the webpage @maniyaom Add gssoc-ext,hactoberfest accepted and level

**Comment by maniyaom** [comment] 2024-10-04 09:52
@rutikakengal This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

You can refer Issue #56 and Issue #71

**Closed by maniyaom** 2024-10-04 09:52 UTC
Labels: duplicate
