### ISSUE TITLE
Fix Homepage bug and Make It Responsive!

### ISSUE THREAD

**Issue by SCR01** [maniyaom/Movie-Ticket-Booking#52] opened 2024-10-02 12:19 UTC
#### Description:
We need to enhance the **homepage login page** to improve its design and functionality, ensuring it is fully responsive across all devices.

#### Why is this important?
- A better-designed login page will improve user experience and engagement.
- Ensuring responsiveness will allow users to access the platform seamlessly from any device.

#### Comment:
- Consider updating the layout and styling for a modern look.
- Implement responsive design principles to ensure the login page adapts well to different screen sizes.
- Test across various devices and browsers for compatibility.

https://github.com/user-attachments/assets/b3f0fa69-c77c-460f-a447-3196d2455ca7

**Comment by SCR01** [comment] 2024-10-02 12:25
Example:

![Screenshot 2024-10-02 175446](https://github.com/user-attachments/assets/ca189def-150f-4eaa-875b-18b582941dfd)

**Comment by maniyaom** [comment] 2024-10-02 13:44
@adityakalburgi This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue 6

**Closed by maniyaom** 2024-10-02 13:44 UTC
Labels: duplicate
