### ISSUE TITLE
[Bug] Movie Genre on Nav Bar

### ISSUE THREAD

**Issue by TanmayKalra09** [maniyaom/Movie-Ticket-Booking#86] opened 2024-10-03 14:03 UTC
Hi @maniyaom while scrolling, the movie genres are visible on the nav bar

Please Assign me this issue under GSSOC Extended and Hacktoberfest :)

https://github.com/user-attachments/assets/d9301fbb-0266-4404-ba2c-736c385fa5f8

**Comment by maniyaom** [comment] 2024-10-03 17:17
@TanmayKalra09 This appears to be a duplicate of an existing issue. Before raising a new issue, please make sure to check the issue section to avoid duplicates.

Reference: Issue #67

**Closed by maniyaom** 2024-10-03 17:17 UTC
Labels: duplicate
